server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuzminal/BookShop-Config-Repo
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true